---
title: Bloom Toolkit
description: This is the main Bloom Toolkit
id: Bloom-Toolkit-E07
highlight: '#EF7145'

defaults:
  public: true
  navigation: false
  #prev: "Anterior"
  #next: "Siguiente"
  pointScale: 10
  passingGrade: 6
