---
title: Numeric Examples
description: Numeric Examples
id: Numeric Examples
highlight: '#EF7145'

defaults:
  locale: es
  navigation: false
  prev: "Anterior"
  next: "Siguiente"
  pointScale: 10
  passingGrade: 6
  public: true
